require('dotenv').config();
const express = require('express');
const cors = require('cors');
const alumnoRoutes = require('./routes/alumnoRoutes');
const app = express();
app.use(cors());
app.use(express.json());
app.use('/api/alumnos', alumnoRoutes);
app.use(express.static('public'));
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log(`Servidor corriendo en puerto ${PORT}`));